apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: "ghcr.io/project-zot/zot-linux-arm64:latest"
    newName: ghcr.io/project-zot/zot-linux-amd64
    newTag: v2.1.2-rc4

resources:
  - deployment.yaml
  - persistent-volume.yaml

configMapGenerator:
  - name: zot-registry-config
    files:
      - config.json
