apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - https://github.com/MichaelTrip/lmsensors-container.git//deployment-files?ref=v1.2.0
  - sensor-dash-ingress.yaml
  - sensor-dash-cert.yaml

patches:
  - path: daemonset-env-patch.yaml
  - path: pvc-patch.yaml
