apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/MichaelTrip/lmsensors-container/refs/tags/v1.2.0/deployment-files/daemonset.yaml
  - https://raw.githubusercontent.com/MichaelTrip/lmsensors-container/refs/tags/v1.2.0/deployment-files/webserver-modern.yaml
  - https://raw.githubusercontent.com/MichaelTrip/lmsensors-container/refs/tags/v1.2.0/deployment-files/configmap.yaml
  - pvc.yaml
  - sensor-dash-ingress.yaml
  - sensor-dash-cert.yaml

patches:
  - path: daemonset-env-patch.yaml
