# service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensordash
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sensordash-privileged
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sensordash-privileged-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sensordash-privileged
subjects:
  - kind: ServiceAccount
    name: sensordash
