apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sensor-dash-tls
spec:
  commonName: sensor-dash.apps.lab-01.okd.home.arpa
  secretName: sensor-dash-tls
  issuerRef:
    name: dontxinkeship-acme
    kind: ClusterIssuer
  dnsNames:
    - sensor-dash.apps.lab-01.okd.home.arpa
