apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: federate-cmo-ms
  namespace: federate-cmo
spec:
  resourceSelector:
    matchLabels:
      monitoring.rhobs/stack: federate-cmo-ms
  logLevel: info
  retention: 3h
  prometheusConfig:
    replicas: 2
  alertmanagerConfig:
    disabled: true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
