namespace: sealed-secrets
ingress:
  enabled: true
  pathType: ImplementationSpecific
  ingressClassName: "openshift-default"
  hostname: sealed-secrets.apps.lab-01.okd.home.arpa
  path: /v1/cert.pem
  tls: false

revisionHistoryLimit: 1

podSecurityContext:
  enabled: true
  fsGroup: null

containerSecurityContext:
  enabled: true
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: null
  capabilities:
    drop:
      - ALL
