extraArgs:
  - --collector.disable-defaults
  - --collector.hwmon
  - --collector.hwmon.chip-exclude=acpitz
  - --log.level=debug

serviceAccount:
  create: true
  name: hwmon-node-exporter

hostNetwork: false
hostPID: false

hostRootFsMount:
  enabled: false

prometheus:
  monitor:
    enabled: true

service:
  port: 9100
  targetPort: 9100
