extraArgs:
  - --collector.disable-defaults
  - --collector.hwmon
  - "--collector.hwmon.chip-include=.*(coretemp|pch_cometlake).*"
  - --log.level=debug

serviceAccount:
  create: true
  name: hwmon-node-exporter

hostNetwork: false
hostPID: false

hostRootFsMount:
  enabled: false

prometheus:
  monitor:
    enabled: true
    relabelings:
      - sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: node

service:
  port: 9100
  targetPort: 9100
