apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lmsensors-container
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xinkecf35/okd-homelab.git
      revision: main
      path: gitops/lmsensors-container/base
  destination:
    server: https://kubernetes.default.svc
    namespace: sensordash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
