apiVersion: apps/v1
kind: Deployment
metadata:
  name: zot-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zot-registry
  template:
    metadata:
      labels:
        app: zot-registry
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "0"
      containers:
        - name: zot
          securityContext: {}
          image: "ghcr.io/project-zot/zot-linux-amd64:v2.1.16"
          imagePullPolicy: IfNotPresent
          env: []
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/lib/registry"
              name: zot-registry-volume
            - mountPath: "/etc/zot"
              name: zot-registry-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: caddy
          securityContext: {}
          image: "docker.io/caddy:2.11.2"
          imagePullPolicy: IfNotPresent
          env: []
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: "/etc/caddy"
              name: caddy-config
            - mountPath: "/usr/local/share/ca-certificates"
              name: donxinkeship-root-ca
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
      volumes:
        - name: zot-registry-volume
          persistentVolumeClaim:
            claimName: zot-registry-volume
        - name: zot-registry-config
          configMap:
            name: zot-registry-config
        - name: caddy-config
          configMap:
            name: caddy-config
        - name: donxinkeship-root-ca
          configMap:
            name: donxinkeship-root-ca

      dnsPolicy: ClusterFirst
