apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pxe-deployment.yaml
  - tftpd-volume.yaml 

configMapGenerator:
  - name: tftpd-pxe-configs
    files:
      - pxelinux.cfg

